### DISCUSSION TITLE
Transfer everything to Github?

### DISCUSSION THREAD

**Discussion by trickert76** [magellan2/magellan2#52] [Ideas]
At the moment, I try to fix the release pipeline. During that process I moved the homepage from magellan.jaatho.de (magellan.narabi.de) to magellan.github.io and replaced the PHP stuff with markdown.

# Bugtracker

During that process, I saw, that we have a bugtracker on http://eressea.dracones.de/magellanbugs/my_view_page.php which is also a personal installation. Actually, Github has an internal issue tracker. I'm not sure, when and why we switched to that external bugtracker. There are 294 bugs reported and 235 are already closed. So, around 50 open issues.

What should we do? Transfer the tasks to Github Issues or stay with that external solution?

# SourceForge

We do have still a project open at SourceForge https://sourceforge.net/projects/magellan-client/. Is it useful to manage two places for release files? Should we just close that project there? But, we still use the mailing list feature of Sourceforge.

# Updater

The new install4j seems to integrate an auto update mechanism. That tool looks into a URL to finde new versions. At the moment, it looks into the Github release site - but very specific to the current release. I think, that is wrong. The update.xml should be placed on the homepage to be version independent. Right?

**Comment by trickert76** [comment]
Ich 'switch' mal auf deutsch.

Ich hab gestern nach langer Zeit wieder PRs bearbeitet und dabei sind mir einige Dinge aufgefallen, die sind Mist. Ursprünglich war es immer so, dass wir Features gesammelt haben und dann in Summe ein Release gemacht haben. Deshalb gibt es master/develop Branches. Aber wenn man vergisst, den develop Branch nach der Release noch mal zu mergen mit Main/Master, dann wird das alles ziemlich ätzend mit den ganzen Konflikten. Das aufzulösen ist nicht schwer, es kostet aber Zeit, die keiner mehr hat.

Ich würde das gerne ändern. Jeder gemerrgte PR führt automatisch zu einer neuen Version.

Damit kommen wir zum nächsten Problem. Versionierung. Das manuell machen, wird nicht gehen, allein schon, weil zwei konkurrierende PRs die neue Versionsnummer in der build.xml statisch hinterlegen müssen. Also muss das in den Buildprozess integriert werden. Idealerweise sollten wir mit Semantic Commits arbeiten, damit Major.Minor.Patch entsprechend sauber iteriert wird. Damit kommen wir aber an das Problem, dass es das für Ant nicht gibt und wir eine weitere Dependency integrieren müssen - NodeJS. Doof eigentlich. Aber es verwenden praktisch alle. Ich hab damit auch schon gute Erfahrungen gesammelt.

Da mir vermutlich keiner widersprechen wird, könnte ich das umstellen. Hier ein paar Snippets

```
npm init -y
npm install --save-dev semantic-release \
  @semantic-release/commit-analyzer \
  @semantic-release/release-notes-generator \
  @semantic-release/changelog \
  @semantic-release/github \
  @semantic-release/git
npm install --save-dev semantic-release-cli
npm install --save-dev @commitlint/config-conventional @commitlint/cli

echo '{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.txt"
      }
    ],
    [
      "@semantic-release/git",
      {
        "assets": ["CHANGELOG.txt", "RELEASENOTES.txt"],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ],
  "@semantic-release/github",
  {
    "assets": [
      { "path": "dist/*.zip" },
      { "path": "build/*.jar" }
    ]
  }
  ]
}
' > .releaserc

echo 'module.exports = {
  extends: ['@commitlint/config-conventional']
};' > commitlint.config.js
```

Im build.yml evtl. umstellen auf:

```
<property name="app.version" value="0.0.0" />

<target name="update_version">
    <echo file="version.txt">${app.version}</echo>
</target>
```

und den Workflow umstellen:

```
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
  
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node installieren
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Dependencies installieren
        run: npm ci

      - name: Version bestimmen
        id: version
        run: |
          VERSION=$(npx semantic-release --dry-run | grep "next release version" | awk '{print $NF}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Release Notes schreiben
        run: |
          echo "${{ steps.version.outputs.version }}" >> RELEASENOTES.txt

      - name: Ant Build
        run: |
          ant -Dapp.version=${{ steps.version.outputs.version }}

      - name: Upload artifacts (CI)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Semantic Release vorbereiten
        id: semantic
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

So oder so ähnlich.
